name: Build Docker Image & Publish to Docker Hub

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Supported PHP versions
        php-version: [ '7.4', '8.0', '8.1', '8.2', '8.3' ]
        # Supported Node.js versions
        node-version: [ '12', '14', '16', '18', '20' ]
        # Exclude unusual combinations of PHP and Node.js versions
        exclude:
          - php-version: '7.4'
            node-version: [ '20' ]
          - php-version: '8.0'
            node-version: [ '12' ]
          - php-version: '8.1'
            node-version: [ '12' ]
          - php-version: '8.2'
            node-version: [ '12' ]
          - php-version: '8.3'
            node-version: [ '12', '14' ]

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ci:${{ matrix.php-version }}-${{ matrix.node-version }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            PHP_VERSION=${{ matrix.php-version }}
            NODE_VERSION=${{ matrix.node-version }}

